name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl pyinstaller xlrd
        
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "CenterPoint File Converter" file_converter.py
        
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: centerpoint-converter-windows
        path: dist/*.exe